# ----------------------------------------------------- 
# Window rules
# ----------------------------------------------------- 

windowrulev2 = tile, title:^(Microsoft-edge)$
windowrule = tile,title:^(Brave-browser)$
windowrule = tile,title:^(Chromium)$
windowrule = float,title:^(pavucontrol)$
windowrule = float,title:^(blueman-manager)$
windowrulev2 = float,title:^(nm-connection-editor)$
windowrule = float,title:^(qalculate-gtk)$
windowrule = float,title:^(io.elementary.settings)$
windowrule = tile,title:^(1Password)$
windowrule = float,title:^(Alacritty)$
windowrule = tile,title:^(kitty)$

windowrule = opacity 0.97,title:^(obsidian)$

# Browser Picture in Picture
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = pin, title:^(Picture-in-Picture)$
windowrulev2 = move 69.5% 4%, title:^(Picture-in-Picture)$
